name: flutter_archkit
description: An automated multi-flavor configuration CLI tool and package for Flutter projects (Android, iOS, VS Code launch, and Dart ServerConfig).
version: 0.0.1
homepage: https://github.com/Sangramdeve/flutter_archkit
repository: https://github.com/Sangramdeve/flutter_archkit
issue_tracker: https://github.com/Sangramdeve/flutter_archkit/issues
topics:
  - flutter
  - flavor
  - generator
  - android
  - ios

environment:
  sdk: ^3.12.2
  flutter: ">=1.17.0"

executables:
  setup_flavor: setup_flavor

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  path: ^1.9.0
  yaml: ^3.1.2
  dart_xcodeproj: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
